# Generated by Django 5.1.6 on 2025-04-20 10:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhiteboardRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhiteboardElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_id', models.CharField(max_length=100)),
                ('element_type', models.CharField(choices=[('path', 'Path'), ('line', 'Line'), ('rect', 'Rectangle'), ('circle', 'Circle'), ('text', 'Text')], max_length=20)),
                ('data', models.JSONField()),
                ('username', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='chat.whiteboardroom')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
