# Generated by Django 5.1.6 on 2025-04-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_whiteboardroom_whiteboardelement'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='background_type',
            field=models.CharField(choices=[('none', 'None'), ('youtube', 'YouTube'), ('upload', 'Upload')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='background_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
